### PR TITLE
Btn accepts a string to change the loading value

### PR DESCRIPTION
**Pull request by tomgatzgates**
Breaking change, will require invite customiser to be updated

### CODE REVIEW

**Comment by tomgatzgates** [comment]
@iest What do you reckon to this? Passing in some plain text to customise the loading state of the button?

**Comment by iest** [comment]
So the loading state comes from a parent component:

```js
var loadingMsg = "Loading something...";
return <Btn isLoading={loadingMsg}/>;
```

Whats the benefit of doing this instead of:

```js
return <Btn>{isLoading ? 'Loading...' : 'Do Something'}</Btn>;
```

It's a nice idea, but I was originally thinking of having a generic loading state with a generic spinner inside the Btn component.

I think I'd rather we had something like this:

```js
const {isLoading} = this.state;
return (
  <Btn isLoading={isLoading}>
    {isLoading ? 'Loading...' : 'Load'}
  </Btn>
);
```

Then inside the button we'd render a spinner with some animation if `isLoading` was true, and always show the children of the button if there was one.

Thoughts?

**Comment by tomgatzgates** [comment]
I agree with option three. Keep the child and is loading just adds a loading spinner

**Comment by iest** [comment]
Gonna close this for now. We can come back to it if we want later.

**Pull request closed without merging**
