### PR TITLE
Helper class for accessibly hidden labels

### PR DESCRIPTION
**Pull request by rdjpalmer**
Global helper class to go someway to solving controls having missing labels: [All controls should have labels, even if they're hidden from sight (but still readable by screen readers)](https://trello.com/c/AwNYhdzH/142-all-controls-should-have-labels-even-if-they-re-hidden-from-sight-but-still-readable-by-screen-readers).

### CODE REVIEW

**Comment by iest** [comment]
Nice one.

What's the argument against having this as a standalone component?

**Comment by rdjpalmer** [comment]
No argument against it: a helper class was the first solution I came to. Any particular reasons you want me to add one?

**Comment by iest** [comment]
Just a more explicit usage e.g. `<AccessibleLabel>Like this coffee</AccessibleLabel`

**Comment by iest** [comment]
I like it. Maybe `label` is the wrong word though?

**Comment by rdjpalmer** [comment]
Yeah, label could be somewhat misleading, as it'll be useful for link text to (e.g., "Read more <hidden>about David Bowie</hidden>).

Some ideas:

1. AccessibleLabel
2. VisuallyHidden
3. AccessibleText - meh
4. AccessibleString - meh

Any thoughts @iest?

**Comment by iest** [comment]
ScreenReadable?

**Comment by rdjpalmer** [comment]
@iest updated

**Comment by iest** [comment]
:ship:

**Pull request merged**
