### PR TITLE
use default checked for toggle

### PR DESCRIPTION
**Pull request by tomgatzgates**

### CODE REVIEW

**Comment by rdjpalmer** [comment]
Do you know all the ramifications of this change? I.e., has it been tested locally with our major `<Toggle />` uses? Everything work as expected?

**Comment by rdjpalmer** [comment]
Oh... you closed it. What's going on?

**Comment by tomgatzgates** [comment]
#104

**Comment by rdjpalmer** [comment]
@tom code is _exactly_ the same?

**Comment by tomgatzgates** [comment]
It was an out of date loggins and I pr'd into master

**Pull request closed without merging**
