### PR TITLE
White hollow buttons are now readable on hover

### PR DESCRIPTION
**Pull request by rdjpalmer**
# Before

btn-white-hollow-before

# After

btn-white-hollow-after

### CODE REVIEW

**Comment by iest** [comment]
:ship:

**Comment by tomgatzgates** [comment]
Why not change font to green? The opacity still makes it hard to read, it's just not impossible any more

**Comment by rdjpalmer** [comment]
@tomgatzgates green isn't versatile enough—if used on a red, blue background it'll clash wildly.

**Comment by tomgatzgates** [comment]
Sorry I meant green due to the background not in all situations. Changing the opacity still isn't readable really. 

Are there any other options that might make the text appear clear/see through to the background colour?

**Comment by rdjpalmer** [comment]
I tried a few things but weren't really happy with them—this is the closest I got. 

An alternative is to refactor the `Btn` component to have a "whiteout" bool which takes `variant`, `type` into account, e.g.:

```jsx
<Btn type="primary" variant="hollow" whiteout>Label</Btn>
```

Which would colour the label as per the `type` prop.

Thoughts @iest, @tomgatzgates?

**Comment by tomgatzgates** [comment]
>I find the opacity tweak still hard to read. A design standard i've seen is where a hollow button, on hover, shows the colour behind as the font colour. As it's usually easier to read. 

That's my feedback, happy for you to ignore it or try and work towards it however, you find easiest :smile:

**Comment by iest** [comment]
At a later date we should completely refactor `Btn`. `type` and `variant` are easily mistakable and interchangeable from each other, and `type` is a valid HTML attribute for use inside forms anyway.

We should add deprecation notices for the use of `type` and `variant` and perhaps move to a [react-bootstrap style](https://react-bootstrap.github.io/components.html#buttons) of doing things. They use `bsStyle` and `bsSize`.

For now though I think we're just bikeshedding. The white button is now more usable. I say ship.

**Comment by rdjpalmer** [comment]
Agreed on `type` and `variant` being mistakable. Got a lot of ways we could improve it though. This was going to get shipped anyway—just didn't get round to it earlier.

**Pull request merged**
